#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# CLI-only / usrmanage-first upgrades must rewrite owned logins to the
# diagnostic 9-set even when luci-app 92 has not run yet (#156 package skew).

[ -f /usr/lib/usrmanage/usrmanage-lib.sh ] || exit 0
# shellcheck disable=SC1091
. /usr/lib/usrmanage/usrmanage-lib.sh

command -v um_luci_login_migrate_observer >/dev/null 2>&1 || exit 0
um_with_lock um_luci_login_migrate_observer || exit 1
exit 0
